export const GET_ALL_DRIVERS = 'GET_ALL_DRIVERS';
export const GET_DRIVER_BY_NAME = 'GET_DRIVER_BY_NAME';
export const GET_DRIVER_BY_ID="GET_DRIVER_BY_ID";
export const GET_ALL_TEAMS="GET_ALL_TEAMS"
export const ORDER_DRIVERS = "ORDER_DRIVERS"; //ORDENAR ASCENDENTE O DESCENDENTE POR ORDEN ALFABETICO y POR FECHA DE NACIMIENTO
export const ORDER_DRIVERS_BY_DOB = "FILTER_API_OR_DB" 
export const FILTER_BY_TEAM = "FILTER_BY_TEAM"; //FILTRA LISTA DE CONDUCTORES POR TEAM
export const FILTER_BY_API_OR_DB = "FILTER_BY_API_OR_DB";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const FETCHED_ERRORS = "FETCHED_ERRORS";




